<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error Handling</title>
</head>
<body>
<script>
    class MathUtil {
        static sum(...numbers) {
            if (numbers.length == 0) {
                throw new Error('Total angka harus lebih dari 0')
            }

            let total = 0
            for (const number of numbers) {
                total += number
            }
            return total
        }
    }

    try {
        console.info(MathUtil.sum(1, 1, 1, 1, 1))
        console.info('Abdurahman')
    } catch (error) {
        console.error(error.message)
    }

    console.info('Rahman')

    //    use try...finally
    class Counter {
        #counter = 1; // with use  private field
        next() {
            try {
                return this.#counter
            } finally {
                this.#counter++
            }
        }
    }

    const counter = new Counter()
    console.info(counter.next())
    console.info(counter.next())
    console.info(counter.next())

</script>
</body>
</html>